#Excel to Properties :de-DE
#Tue Nov 26 21:14:31 CST 2024
STATION_ID_IS_MUST=Anlagen-ID erforderlich.
NO_CHOOSE_TYPE=Bitte geben Sie das abzufragende Modul ein
NOT_ONE_DATA=Bitte \u00FCberpr\u00FCfen Sie die Sprache unter den gleichen Daten
DELETE_TOPIC_ERROR=L\u00F6schung fehlgeschlagen. Die Daten werden noch verwendet.
LOCALE_ERROR=Bitte \u00FCberpr\u00FCfen Sie die Sprachumgebung
CUSTOMER_1005_CONTACT_INFORMATION_NULL=Kontakt erforderlich. Bitte eingeben.
