#Excel to Properties :fr-FR
#Tue Nov 26 21:14:31 CST 2024
STATION_ID_IS_MUST=L'ID du site est obligatoire.
NO_CHOOSE_TYPE=Veuillez saisir le module \u00E0 interroger
NOT_ONE_DATA=intentionnellement laiss\u00E9 vierge
DELETE_TOPIC_ERROR=La suppression a \u00E9chou\u00E9. Les donn\u00E9es sont toujours utilis\u00E9es.
LOCALE_ERROR=Please check the language environment
CUSTOMER_1005_CONTACT_INFORMATION_NULL=Le contact est requis, veuillez le saisir.
