#Excel to Properties :de-DE
#Wed Nov 27 12:01:35 CST 2024
PARAM_ERROR=Parameterfehler aufgetreten.
DELETE_ERROR_SENDED=L\u00F6schen fehlgeschlagen\: Mitteilung wurde gesendet.
UPDATE_ERROR_SENDED=Aktualisierung fehlgeschlagen\: Mitteilung wurde gesendet.
MESSAGE_MODEL_ERROR=Fehler beim Abrufen des entsprechenden Typencodes, bitte \u00FCberpr\u00FCfen Sie, ob eine entsprechende Vorlage oder die Vorlagenkonfiguration korrekt ist.
