#Excel to Properties :fr-FR
#Wed Nov 27 12:01:35 CST 2024
PARAM_ERROR=Une erreur de param\u00E8tre s\u2019est produite.
DELETE_ERROR_SENDED=\u00C9chec de la suppression\u00A0\: l'annonce envoy\u00E9e
UPDATE_ERROR_SENDED=\u00C9chec de la mise \u00E0 jour\u00A0\: l'annonce envoy\u00E9e
MESSAGE_MODEL_ERROR=Une erreur s'est produite lors de l'obtention du code de type correspondant. Veuillez v\u00E9rifier si le mod\u00E8le correspondant existe ou si la configuration du mod\u00E8le est correcte.
