#Excel to Properties :en-US
#Wed Nov 27 12:01:35 CST 2024
PARAM_ERROR=Parameter error occurred.
DELETE_ERROR_SENDED=Deletion failed\: Announcement sent.
UPDATE_ERROR_SENDED=Update failed\: Announcement sent.
MESSAGE_MODEL_ERROR=Error occurred in obtaining the corresponding type code. Please check whether the corresponding template exists or the template configuration is correct.
