#Excel to Properties :pl-PL
#Wed Nov 27 12:01:35 CST 2024
PARAM_ERROR=Wyst\u0105pi\u0142 b\u0142\u0105d parametru.
DELETE_ERROR_SENDED=Niepowodzenie usuwania\: wys\u0142ano powiadomienie
UPDATE_ERROR_SENDED=Niepowodzenie aktualizacji\: wys\u0142ano powiadomienie
MESSAGE_MODEL_ERROR=Wyst\u0105pi\u0142 b\u0142\u0105d przy uzyskiwaniu odpowiedniego rodzaju kodu. Sprawd\u017A, czy istnieje odpowiedni szablon lub czy konfiguracja szablonu jest prawid\u0142owa
