#Excel to Properties :es-ES
#Wed Nov 27 12:01:35 CST 2024
PARAM_ERROR=Se ha producido un error de par\u00E1metro.
DELETE_ERROR_SENDED=No se ha podido borrar\: anuncio enviado
UPDATE_ERROR_SENDED=No se ha podido actualizar\: anuncio enviado
MESSAGE_MODEL_ERROR=Se ha producido un error al obtener el c\u00F3digo de tipo correspondiente. Revise si dispone de la plantilla correspondiente o la configuraci\u00F3n de la plantilla es correcta.
