#Excel to Properties :it-IT
#Wed Nov 27 12:01:35 CST 2024
PARAM_ERROR=Si \u00E8 verificato un errore nei parametri.
DELETE_ERROR_SENDED=Eliminazione non riuscita\: annuncio inviato
UPDATE_ERROR_SENDED=Aggiornamento non riuscito\: annuncio inviato
MESSAGE_MODEL_ERROR=Si \u00E8 verificato un errore nell'ottenimento del codice tipo corrispondente. Controllare se il modello corrispondente esiste o se la configurazione del modello \u00E8 corretta
