#Excel to Properties :pl-PL
#Wed Nov 27 15:13:45 CST 2024
EXPORT_FAIL=Wyst\u0105pi\u0142 b\u0142\u0105d eksportu pliku
LOCALE_ERROR=Sprawd\u017A \u015Brodowisko j\u0119zykowe
FILE_NAME_IS_MUST=Wymagana jest nazwa pliku. Sprawd\u017A
SYSTEM_LOG_MODULE_FUNCTION=Modu\u0142 funkcjonalny
SYSTEM_LOG_OPERATION_NAME=Operacja
SYSTEM_LOG_LEVEL=Poziom
SYSTEM_LOG_OPERATING_USERS=Operator
SYSTEM_LOG_OPERATING_PLAT=Platforma robocza
SYSTEM_LOG_TERMINAL=Terminal
SYSTEM_LOG_OPERATING_TIME=Uruchomiono
SYSTEM_LOG_RESULT=Wynik
SYSTEM_LOG_DETAILS=Szczeg\u00F3\u0142y
SYSTEM_LOG_LEVEL_FATAL=Krytyczne
SYSTEM_LOG_LEVEL_SERIOUS=Powa\u017Cne
SYSTEM_LOG_LEVEL_COMMONLY=Mniej powa\u017Cne
SYSTEM_LOG_LEVEL_TIP=Ostrze\u017Cenie
SYSTEM_LOG_RESULT_SUCCESSFUL=Pomy\u015Blne
SYSTEM_LOG_RESULT_FAILED=Niepowodzenie
SYSTEM_LOG_DOWNLOAD_SYSTEM=Dziennik systemu
SYSTEM_LOG_DOWNLOAD_SECURITY=Dziennik bezpiecze\u0144stwa
SYSTEM_LOG_DOWNLOAD_OPERATE=Dziennik OS
