#Excel to Properties :zh-CN
#Wed Nov 27 15:13:45 CST 2024
EXPORT_FAIL=\u6587\u4EF6\u5BFC\u51FA\u9519\u8BEF
LOCALE_ERROR=\u8BF7\u68C0\u67E5\u8BED\u8A00\u73AF\u5883
FILE_NAME_IS_MUST=\u6587\u4EF6\u540D\u79F0\u4E0D\u80FD\u4E3A\u7A7A\uFF0C\u8BF7\u4FEE\u6539
SYSTEM_LOG_MODULE_FUNCTION=\u529F\u80FD\u6A21\u5757
SYSTEM_LOG_OPERATION_NAME=\u64CD\u4F5C\u540D\u79F0
SYSTEM_LOG_LEVEL=\u7EA7\u522B
SYSTEM_LOG_OPERATING_USERS=\u64CD\u4F5C\u7528\u6237
SYSTEM_LOG_OPERATING_PLAT=\u64CD\u4F5C\u5E73\u53F0
SYSTEM_LOG_TERMINAL=\u7EC8\u7AEF
SYSTEM_LOG_OPERATING_TIME=\u64CD\u4F5C\u65F6\u95F4
SYSTEM_LOG_RESULT=\u7ED3\u679C
SYSTEM_LOG_DETAILS=\u8BE6\u60C5
SYSTEM_LOG_LEVEL_FATAL=\u81F4\u547D
SYSTEM_LOG_LEVEL_SERIOUS=\u4E25\u91CD
SYSTEM_LOG_LEVEL_COMMONLY=\u4E00\u822C
SYSTEM_LOG_LEVEL_TIP=\u63D0\u793A
SYSTEM_LOG_RESULT_SUCCESSFUL=\u6210\u529F
SYSTEM_LOG_RESULT_FAILED=\u5931\u8D25
SYSTEM_LOG_DOWNLOAD_SYSTEM=\u7CFB\u7EDF\u65E5\u5FD7
SYSTEM_LOG_DOWNLOAD_SECURITY=\u5B89\u5168\u65E5\u5FD7
SYSTEM_LOG_DOWNLOAD_OPERATE=\u64CD\u4F5C\u65E5\u5FD7
