#Excel to Properties :es-ES
#Wed Nov 27 15:13:45 CST 2024
EXPORT_FAIL=Error al exportar el archivo.
LOCALE_ERROR=Compruebe el entorno de idioma.
FILE_NAME_IS_MUST=El nombre del archivo no puede dejarse en blanco. Modif\u00EDquelo.
SYSTEM_LOG_MODULE_FUNCTION=M\u00F3dulo funcional
SYSTEM_LOG_OPERATION_NAME=Operaci\u00F3n
SYSTEM_LOG_LEVEL=Nivel
SYSTEM_LOG_OPERATING_USERS=Operador
SYSTEM_LOG_OPERATING_PLAT=Plataforma operativa
SYSTEM_LOG_TERMINAL=Terminal
SYSTEM_LOG_OPERATING_TIME=Operado a las
SYSTEM_LOG_RESULT=Resultado
SYSTEM_LOG_DETAILS=Detalles
SYSTEM_LOG_LEVEL_FATAL=Cr\u00EDtico
SYSTEM_LOG_LEVEL_SERIOUS=Grave
SYSTEM_LOG_LEVEL_COMMONLY=Leve
SYSTEM_LOG_LEVEL_TIP=Aviso
SYSTEM_LOG_RESULT_SUCCESSFUL=\u00C9xito
SYSTEM_LOG_RESULT_FAILED=Fallo
SYSTEM_LOG_DOWNLOAD_SYSTEM=Registro del sistema
SYSTEM_LOG_DOWNLOAD_SECURITY=Registro de seguridad
SYSTEM_LOG_DOWNLOAD_OPERATE=Registro del sistema operativo
