#Excel to Properties :de-DE
#Wed Nov 27 15:13:45 CST 2024
EXPORT_FAIL=Fehler beim Dateiexport.
LOCALE_ERROR=Bitte die Sprachumgebung \u00FCberpr\u00FCfen.
FILE_NAME_IS_MUST=Dateiname erforderlich, bitte bearbeiten.
SYSTEM_LOG_MODULE_FUNCTION=Funktionsmodul
SYSTEM_LOG_OPERATION_NAME=Vorgang
SYSTEM_LOG_LEVEL=Stufe
SYSTEM_LOG_OPERATING_USERS=Bediener
SYSTEM_LOG_OPERATING_PLAT=Betriebsplattform
SYSTEM_LOG_TERMINAL=Endger\u00E4t
SYSTEM_LOG_OPERATING_TIME=Bedient am
SYSTEM_LOG_RESULT=Ergebnis
SYSTEM_LOG_DETAILS=Details
SYSTEM_LOG_LEVEL_FATAL=Kritisch
SYSTEM_LOG_LEVEL_SERIOUS=Ernst
SYSTEM_LOG_LEVEL_COMMONLY=Weniger wichtig
SYSTEM_LOG_LEVEL_TIP=Warnung
SYSTEM_LOG_RESULT_SUCCESSFUL=Erfolgreich
SYSTEM_LOG_RESULT_FAILED=Fehlgeschlagen
SYSTEM_LOG_DOWNLOAD_SYSTEM=Systemprotokoll
SYSTEM_LOG_DOWNLOAD_SECURITY=Sicherheitsprotokoll
SYSTEM_LOG_DOWNLOAD_OPERATE=Betriebssystem-Protokoll
