#Excel to Properties :it-IT
#Wed Nov 27 15:13:45 CST 2024
EXPORT_FAIL=Si \u00E8 verificato un errore durante l'esportazione del file
LOCALE_ERROR=Controlla l'ambiente linguistico
FILE_NAME_IS_MUST=Il nome del file \u00E8 obbligatorio. Controlla
SYSTEM_LOG_MODULE_FUNCTION=Modulo funzionale
SYSTEM_LOG_OPERATION_NAME=Operazione
SYSTEM_LOG_LEVEL=Livello
SYSTEM_LOG_OPERATING_USERS=Operatore
SYSTEM_LOG_OPERATING_PLAT=Piattaforma operativa
SYSTEM_LOG_TERMINAL=Terminale
SYSTEM_LOG_OPERATING_TIME=Operato in
SYSTEM_LOG_RESULT=Risultato
SYSTEM_LOG_DETAILS=Dettagli
SYSTEM_LOG_LEVEL_FATAL=Critico
SYSTEM_LOG_LEVEL_SERIOUS=Grave
SYSTEM_LOG_LEVEL_COMMONLY=Minore
SYSTEM_LOG_LEVEL_TIP=Avvertenza
SYSTEM_LOG_RESULT_SUCCESSFUL=Riuscito
SYSTEM_LOG_RESULT_FAILED=Non riuscito
SYSTEM_LOG_DOWNLOAD_SYSTEM=Log di sistema
SYSTEM_LOG_DOWNLOAD_SECURITY=Log di sicurezza
SYSTEM_LOG_DOWNLOAD_OPERATE=Log del sistema operativo
